### ISSUE TITLE
ビルドコマンドに失敗する

### ISSUE THREAD

**Issue by udonc** [udonc/bsky_hashtag#8]
```sh
> bsky_hashtag@0.0.0 build /home/udon/repo/github/udonc/bsky_hashtag
> tsc && vite build

vite v5.1.0 building for production...
✓ 2 modules transformed.
error during build:
RollupError: Could not resolve entry module "popup.html".
    at error (file:///home/udon/repo/github/udonc/bsky_hashtag/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.loadEntryModule (file:///home/udon/repo/github/udonc/bsky_hashtag/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:18043:20)
    at async Promise.all (index 0)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by udonc** [comment]
`public/popup.html` を `src/popup.html` にリネームすると治ると思う
